import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'

const primaryFont = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'exorcisindemon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={primaryFont.className}>{children}</body>
    </html>
  )
}
